### ISSUE TITLE
Support specific question invocation

### ISSUE THREAD

**Issue by grebenyuksv** [eignatenkov/chgk_bot#39]
Dear Egor, I'm a huge fan of your bot. What do you think about the following feature? I'd be happy to submit a PR. You might also have better ideas about the implemention.

Feature. Bring up specific messages with `/message <message-id>`.

Use case. A want to share the questions I liked with my team chat and let them play.

**Comment by eignatenkov** [comment]
Эм. Я не очень понимаю, что ты хочешь. Почему нельзя просто отфорвардить сообщение с текстом вопроса в нужный тебе чат?

**Comment by grebenyuksv-preply** [comment]
Это геморно, потому что сам выполняешь работу бота.

Ситуация А: я знаю ответ. Руками отвечаю всей команде да/нет.

Ситуация Б: я еще сам играю вопрос, не могу его взять, подключаю команду. В таком случае, если им просто отфорвардить сообщение — еще и приходится вбивать в персональный канал с ботом все их версии и сообщать им результаты.

**Comment by eignatenkov** [comment]
ты не путаешь моего бота с каким-то другим? Мой не умеет версии обрабатывать.

**Comment by grebenyuksv-preply** [comment]
Блиииин, да, с `@chgk_bot` :D Прости, закрывай
